[package]
name = "app"
version = "0.1.0"
edition = "2021"
authors = ["m1ckc3b"]

[[bin]]
name = "code-breaker"
path = "src/main.rs"

[dependencies]
rand = "0.9.0"
iocraft = "0.6.2"
chrono = { version = "0.4.39", features = ["serde"] }